#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{branch}-{build}'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
- Visual Studio 2017

# set clone depth
clone_depth: 1

# clone directory
clone_folder: c:\projects\rpcpp_plugins

# scripts that are called at very beginning, before repo cloning
init:
- ps: >-
    if (Test-Path env:TRIGGER_NAME) {
        Update-AppveyorBuild -Message "Build from $env:TRIGGER_COMMIT in $env:TRIGGER_NAME"
    } else {
        Set-AppveyorBuildVariable -Name 'TRIGGER_NAME' -Value "$env:APPVEYOR_PROJECT_NAME"
        Set-AppveyorBuildVariable -Name 'TRIGGER_COMMIT' -Value "$env:APPVEYOR_REPO_COMMIT".substring(0, 8)
    }
- git --version
- cmake --version

# environment variables
environment:
    CMAKE_PREFIX_PATH: C:\projects\_install;C:\projects\_cache;
    BOOST_ROOT: C:\Libraries\boost_1_64_0

# scripts that run after cloning repository
install:
- ps: (mkdir C:\projects\_install) -and (pushd C:\projects\_install)
- ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/bluekyu/panda3d/artifacts/panda3d.7z?branch=develop'
- 7z x -y panda3d.7z > nul
- ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/bluekyu/render-pipeline-cpp/artifacts/render_pipeline_cpp.7z?branch=master'
- 7z x -y render_pipeline_cpp.7z > nul
- ps: popd

# build cache to preserve files/folders between builds
cache:
- C:\projects\_cache

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
- Release

build:
    parallel: true                  # enable MSBuild parallel builds

# to run your custom scripts instead of automatic MSBuild
build_script:
- ps: (mkdir _build) -and (pushd _build)
- cmd: >-
    cmake -Wno-dev ..
    -DCMAKE_INSTALL_PREFIX="C:/projects/_install/rpcpp_plugins"
    -DBoost_USE_STATIC_LIBS:BOOL=ON
    -Dpanda3d_ROOT:PATH="C:/projects/_install/panda3d"
    -Drpcpp_plugins_BUILD_background2d:BOOL=ON
- cmake --build . --config %CONFIGURATION% --target install
- cmd: >-
    cmake -Wno-dev ..
    -DCMAKE_INSTALL_PREFIX="C:/projects/_install/render_pipeline_cpp"
- cmake --build . --config %CONFIGURATION% --target install
- ps: popd

after_build:
- 7z a rpcpp_plugins.7z "C:/projects/_install/rpcpp_plugins"

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to disable automatic tests
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: rpcpp_plugins.7z

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:
- ps: >-
    Start-AppveyorBuild -ApiKey $env:api_key -ProjectSlug 'rpcpp-samples' -EnvironmentVariables @{
        TRIGGER_NAME = $env:TRIGGER_NAME
        TRIGGER_COMMIT = $env:TRIGGER_COMMIT
    }
