information:
    category: rendering
    name: OpenVR
    author: Younguk Kim <yukim@chic.re.kr>
    version: 0.1
    description: >
        A plugin to support OpenVR.

settings: !!omap

    - distance_scale:
        type: float
        range: [0.001, 1000.0]
        default: 5.0
        runtime: true
        label: Distance Scale
        description: >
            This setting scales the distance that is used from OpenVR in meter scale.

    - supersample_mode:
        type: enum
        values: ["auto", "force", "ignore"]
        default: auto
        shader_runtime: false
        label: Supersample Mode
        description: >
            This setting sets how to apply supersample scale in SteamVR.
            "auto" mode uses supersample in SteamVR with additional scale of supersample_scale setting.
            "force" mode uses only scale of supersample_scale setting and ignore that in SteamVR.
            "ignore" mode ignore all scale of supersample. That is, target size uses Render Pipeline resolution.

    - supersample_scale:
        type: float
        range: [0.001, 100.0]
        default: 1.0
        runtime: true
        label: Supersample Scale
        description: >
            This setting sets scale of supersample scale in SteamVR. See Supersample Mode for detail.

    - supersample_scale_min:
        type: float
        range: [0.001, 100.0]
        default: 1.0
        shader_runtime: false
        label: Minimum Value of Supersample Scale
        description: >
            This setting sets minimum value of scale of supersample scale in SteamVR.

    - enable_rendering:
        type: bool
        default: true
        shader_runtime: false
        label: Enable VR rendering
        description: >
            This setting indicates whether it uses OpenVR rendering, or not.
            If you want to only track devices, set 'false'.
            However, this does not affect the pose of camera. If you want to disable it,
            set 'update_camera_pose' to false.

    - update_camera_pose:
        type: bool
        default: true
        shader_runtime: false
        label: Update Camera Pose
        description: >
            This setting indicates whether the pose of camera should be updated from
            HMD pose, or not.

    - update_eye_pose:
        type: bool
        default: true
        shader_runtime: false
        label: Update Eye Pose
        description: >
            This setting indicates whether the pose of eyes should be updated from
            HMD eye pose, or not.

    - create_device_node:
        type: bool
        default: true
        shader_runtime: false
        label: Create nodes for the tracked devices.
        description: >
            This setting indicates whether create nodes for the tracked devices of OpenVR, or not.

    - load_render_model:
        type: bool
        default: true
        shader_runtime: false
        label: Load rendering models of OpenVR
        description: >
            This setting indicates whether load the rendering models of OpenVR, or not.

    - enable_controller:
        type: bool
        default: true
        shader_runtime: false
        label: Enable OpenVR Controller
        description: >
            This setting indicates whether enable OpenVRController, or not.

    - openvr_sdk_path:
        type: path
        runtime: false
        label: SDK directory path to load OpenVR DLL
        description: >
            This setting is used for base path to load OpenVR DLL in only Windows.
            The value is used as Filename in Panda3D and
            if this value is empty, then plugin will not load OpenVR DLL.
