information:
    category: rendering
    name: OpenVR
    author: Younguk Kim <yukim@chic.re.kr>
    version: 0.1
    description: >
        A plugin to support OpenVR.

settings: !!omap

    - distance_scale:
        type: float
        range: [0.001, 1000.0]
        default: 5.0
        shader_runtime: false
        label: Distance Scale
        description: >
            This setting scales the distance that is used from OpenVR in meter scale.

    - update_camera_pose:
        type: bool
        default: true
        shader_runtime: false
        label: Update Camera Pose
        description: >
            This setting indicates whether the pose of camera should be updated from
            HMD pose, or not.

    - update_eye_pose:
        type: bool
        default: true
        shader_runtime: false
        label: Update Eye Pose
        description: >
            This setting indicates whether the pose of eyes should be updated from
            HMD eye pose, or not.

    - load_render_model:
        type: bool
        default: true
        shader_runtime: false
        label: Load rendering models of OpenVR.
        description: >
            This setting indicates whether load the rendering models of OpenVR, or not.
